### PR TITLE
Update 02.PPO.ipynb

### PR DESCRIPTION
**Pull request by fbarez**
fixed typo

### CODE REVIEW

**Review by Curt-Park — APPROVED** [review]
Looks good

**Comment by Curt-Park** [comment]
@MrSyee Please check this and consider to add @fbarez as a contributor.

**Comment by MrSyee** [comment]
@all-contributors add fbarez for maintainance

**Comment by MrSyee** [comment]
OK. But all-contributors module has a tiny problem... So I'll add @fbarez as a contributor soon after merge this PR.

**Comment by fbarez** [comment]
Thanks @MrSyee.

**Comment by MrSyee** [comment]
@all-contributors add @fbarez for maintainance

**Comment by MrSyee** [comment]
@all-contributors add @fbarez for maintenance

**Pull request merged**
