### PR TITLE
Add A2C

### PR DESCRIPTION
**Pull request by mclearning2**
I didn't use ActionNormaliezr and Gaussian distribution. Because It hurts performance and stability. These are my experiments for comparing performance. But I don't know what affects this. You can see this code in [Colab](https://colab.research.google.com/github/MrSyee/pg-is-all-you-need/blob/feature%2Fadd-a2c/02.A2C.ipynb).

## Without ActionNormalizer, with normal distribution
- mu * 2
- action clip -2, 2
- The activation function of log_std is softplus

### CODE REVIEW

**Comment by Curt-Park** [comment]
Please add a direct link to Colab so as to easily review.

**Comment by mclearning2** [comment]
Ok, give me a second(actually 5 minute)

**Comment by Curt-Park** [comment]
@mclearning2 Don't be hurry. Take your time.

**Comment by mclearning2** [comment]
@Curt-Park I added colab

**Comment by Curt-Park** [comment]
The link is read-only. I cannot run.

**Comment by Curt-Park** [comment]
Please link Colab to the file on your feature branch but the file on your Google drive. It doesn't show the recent changes in your PR.

**Comment by mclearning2** [comment]
Is [this](https://colab.research.google.com/github/MrSyee/pg-is-all-you-need/blob/feature%2Fadd-a2c/02.A2C.ipynb) correct?

**Comment by Curt-Park** [comment]
@mclearning2 Yes it is

**Comment by Curt-Park** [comment]
1. align the imports. (isort plugin)
2. Cannot run on GPU (train)

> /usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:1374: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
>   warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> /usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
>      55     try:
> ---> 56         return getattr(obj, method)(*args, **kwds)
>      57 
> 
> AttributeError: 'Tensor' object has no attribute 'clip'
> 
> During handling of the above exception, another exception occurred:
> 
> TypeError                                 Traceback (most recent call last)
> 7 frames
> /usr/local/lib/python3.6/dist-packages/torch/tensor.py in __array__(self, dtype)
>     456     def __array__(self, dtype=None):
>     457         if dtype is None:
> --> 458             return self.numpy()
>     459         else:
>     460             return self.numpy().astype(dtype, copy=False)
> 
> TypeError: c1. align the imports. (isort plugin)
> 2. an't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**Review by mclearning2 — COMMENTED** [review]
I fixed it to enable to run the code in the GPU. And run `isort -y`

**Comment by Curt-Park** [comment]
Offline review is done. Please update

**Comment by mclearning2** [comment]
@Curt-Park @MrSyee I added a description of the advantage and the entropy. please check it and approve this PR

**Comment by Curt-Park** [comment]
1. _Italic_ is better than **bold** when you write in English.
2. ~~Lastly,~~ We call the policy _Actor_**,** which predicts probabilities of actions in each state, and **call** the value function ~~is~~ _Critic_**,** which predicts values of all state-action pairs.
3. It would be better to use two subtitles (Actor-Critic, Advantage Function, Maximization Entropy) for the description of A2C. Plus, remove ~~As mentioned above~~
4. Passive sentences are not so proper, especially in academic writing.
The advantage function ~~is used for reducing~~ **effectively** reduces **the** variance of values ~~. It's~~ **and is** defined ~~like this~~ as follows.
5. Don't use conjunctions like conjunctive adverbs (But / So). 
But => However,
So => As a result,
6. Too tedious.
~~But There is a problem that we need to implement two models for action value  𝑄  and state value  𝑉 . Fortunately, we can use the TD error by replacing  𝑄  with ~~
=> From this formula, we can replace Q with 𝑟+𝛾𝑉(𝑠′) and redefine Advantage function without using Action-Value function.
7. ~~The~~ **E**ntropy is a measure of unpredictability or **a** measure of randomness.
8. ~~When~~ we have actions with almost equal probabilities, the entropy over actions ~~will be high.~~
=> **If** we have actions with equal probabilities, the entropy over **the** actions will be the largest because it's completely unpredictable which action will be chosen.
9. ~~So, It can be used to encourage exploration by adding the entropy to the loss.~~
In view of the fact, we can encourage exploration by adding entropy maximization term to the loss function.
10. ~~The entropy  𝐻  respect to a probability  𝑝(𝑎)  of an action  𝑎  is~~
The entropy 𝐻 with respect to the probability p over actions is 
11. Here is a summary of **A2C**Agent class.
12. This line is too long.
`policy_loss = -advantage.detach() * log_prob  # adv. is not backpropagated`
13. `# potting` => `# plot`
14. Remove this line. `targ_value = targ_value`
15. We need to detach the target value?
value_loss = F.smooth_l1_loss(pred_value, targ_value.**detach()**)
16. Add descriptions for optimizers in the A2C docstring.
17. Add a docstring of init method.

**Comment by Curt-Park** [comment]
I suggest this approach regarding updating. Preceding value function update usually makes better results, so people generally do as follows. (Just suggestion. Choice is yours.)
```
def update_model(self) -> Tuple[torch.Tensor, torch.Tensor]:
        state, log_prob, next_state, reward, done = self.transition

        # Q_t   = r + gamma * V(s_{t+1})  if state != Terminal
        #       = r                       otherwise
        mask = 1 - done
        next_state = torch.FloatTensor(next_state).to(self.device)
        pred_value = self.critic(state)
        targ_value = reward + self.gamma * self.critic(next_state) * mask
        value_loss = F.smooth_l1_loss(pred_value, targ_value.detach())
        
        # update value
        self.critic_optimizer.zero_grad()
        value_loss.backward()
        self.critic_optimizer.step()

        # advantage = Q_t - V(s_t)
        pred_value = self.critic(state)
        advantage = (targ_value - pred_value).detach()  # not backpropagated
        policy_loss = -advantage * log_prob
        policy_loss += self.entropy_weight * -log_prob  # entropy maximization

        # update policy
        self.actor_optimizer.zero_grad()
        policy_loss.backward()
        self.actor_optimizer.step()

        return policy_loss.item(), value_loss.item()
```

download

**Comment by Curt-Park** [comment]
When executing the test method, the following error occurs a lot. Please check.

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-17-8888c83ca256> in <module>()
----> 1 frames = agent.test()

4 frames
/usr/local/lib/python3.6/dist-packages/pyglet/gl/__init__.py in <module>()
    225     else:
    226         from .carbon import CarbonConfig as Config
--> 227 del base
    228 
    229 # XXX remove

NameError: name 'base' is not defined
```

**Comment by mclearning2** [comment]
@Curt-Park I tried to run the colab in other develope environments. But It didn't happen to me.
@MrSyee Please Check this

image

**Comment by Curt-Park** [comment]
@mclearning2 I will test again after you modify it.

**Comment by mclearning2** [comment]
Thank you(@Curt-Park), for your detailed review. I edited the descriptions you mentioned and run the agent one more time to compare. As a result, it looks similar but I changed the code without a single duplicated line of code because your suggestions are easier to read.

```
def update_model(self) -> Tuple[torch.Tensor, torch.Tensor]:
        state, log_prob, next_state, reward, done = self.transition

        # Q_t   = r + gamma * V(s_{t+1})  if state != Terminal
        #       = r                       otherwise
        mask = 1 - done
        next_state = torch.FloatTensor(next_state).to(self.device)
        pred_value = self.critic(state)
        targ_value = reward + self.gamma * self.critic(next_state) * mask
        value_loss = F.smooth_l1_loss(pred_value, targ_value.detach())
        
        # update value
        self.critic_optimizer.zero_grad()
        value_loss.backward()
        self.critic_optimizer.step()

        # advantage = Q_t - V(s_t)
        <<<<<<<<<<<<<<< pred_value = self.critic(state) >>>>>>>>>>>>>>>>>>>
        advantage = (targ_value - pred_value).detach()  # not backpropagated
        policy_loss = -advantage * log_prob
        policy_loss += self.entropy_weight * -log_prob  # entropy maximization

        # update policy
        self.actor_optimizer.zero_grad()
        policy_loss.backward()
        self.actor_optimizer.step()

        return policy_loss.item(), value_loss.item()
```

### Before
image



### After
image

**Comment by Curt-Park** [comment]
1. Check this
```
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-18-4326fee8443c> in <module>()
----> 1 agent.train(num_frames)

1 frames
<ipython-input-14-64d9ebe62916> in update_model(self)
     76         next_state = torch.FloatTensor(next_state).to(self.device)
     77         targ_value = reward + self.gamma * self.critic(next_state) * mask
---> 78         value_loss = F.smooth_l1_loss(pred_value, targ_value.detach())
     79 
     80         # update value

UnboundLocalError: local variable 'pred_value' referenced before assignment
```

2. I hope you change the bold words to italic.

**Comment by Curt-Park** [comment]
update method looks like this on my execution.

```
    def update_model(self) -> Tuple[torch.Tensor, torch.Tensor]:
        state, log_prob, next_state, reward, done = self.transition

        # Q_t   = r + gamma * V(s_{t+1})  if state != Terminal
        #       = r                       otherwise
        mask = 1 - done
        next_state = torch.FloatTensor(next_state).to(self.device)
        targ_value = reward + self.gamma * self.critic(next_state) * mask
        value_loss = F.smooth_l1_loss(pred_value, targ_value.detach())
        
        # update value
        self.critic_optimizer.zero_grad()
        value_loss.backward()
        self.critic_optimizer.step()

        # advantage = Q_t - V(s_t)
        pred_value = self.critic(state)
        advantage = (targ_value - pred_value).detach()  # not backpropagated
        policy_loss = -advantage * log_prob
        policy_loss += self.entropy_weight * -log_prob  # entropy maximization

        # update policy
        self.actor_optimizer.zero_grad()
        policy_loss.backward()
        self.actor_optimizer.step()

        return policy_loss.item(), value_loss.item()
```

**Comment by mclearning2** [comment]
@Curt-Park Oh! It was my mistake! prev_value must be up like this, and I misunderstood to change *italic* to **bold**. I'll fix it.

    def update_model(self) -> Tuple[torch.Tensor, torch.Tensor]:
        state, log_prob, next_state, reward, done = self.transition

        # Q_t   = r + gamma * V(s_{t+1})  if state != Terminal
        #       = r                       otherwise
        mask = 1 - done
        **pred_value = self.critic(state)**
        next_state = torch.FloatTensor(next_state).to(self.device)
        targ_value = reward + self.gamma * self.critic(next_state) * mask
        value_loss = F.smooth_l1_loss(pred_value, targ_value.detach())
        
        # update value
        self.critic_optimizer.zero_grad()
        value_loss.backward()
        self.critic_optimizer.step()

        # advantage = Q_t - V(s_t)
        ~~pred_value = self.critic(state)~~
        advantage = (targ_value - pred_value).detach()  # not backpropagated
        policy_loss = -advantage * log_prob
        policy_loss += self.entropy_weight * -log_prob  # entropy maximization

        # update policy
        self.actor_optimizer.zero_grad()
        policy_loss.backward()
        self.actor_optimizer.step()

        return policy_loss.item(), value_loss.item()

**Comment by Curt-Park** [comment]
minor comment in the following table.

Method | Note
-- | --
select_action | select an action from the input state.
step | take an action and return the response of the env.
update_model | update the model by gradient descent.
train | train the agent during num_frames.
test | test the agent (1 episode).
**_plot** | plot the training progresses.

**Review by Curt-Park — APPROVED** [review]
Test is done. It's so well done.
Btw, please check the last (minor) comment.

**Comment by MrSyee** [comment]
I check complete.

**Pull request merged**
