### PR TITLE
Add TD3

### PR DESCRIPTION
**Pull request by mclearning2**
I have implemented TD3 and it performs very well. Added documentation on Gaussian noise. However, I don't know exactly about TD3, so I will add documents soon.

image

Here is [Colab](https://colab.research.google.com/github/MrSyee/pg-is-all-you-need/blob/feature/add-td3/04.TD3.ipynb#scrollTo=mP7xQBoSvzlz)

### CODE REVIEW

**Comment by Curt-Park** [comment]
I will review this after you add all descriptions.

**Comment by MrSyee** [comment]
@Curt-Park @mclearning2

I'll add all descriptions by September 29th as discussed.

**Comment by MrSyee** [comment]
@Curt-Park @mclearning2 
Sorry, I didn't finish yet. I'll finish tonight.

**Comment by MrSyee** [comment]
@Curt-Park @mclearning2 
I've written its document. Please review.

**Comment by Curt-Park** [comment]
@MrSyee Okay. Today, I will.

**Comment by Curt-Park** [comment]
1. this paper propose a clipped Double Q-learning.
=> proposes
2. applied to the state of the art actor-critic method for continuous control, Deep Deterministic Policy Gradient algorithm (DDPG)
=> DDPG is not a state of the art method now.
3. the recent success of DQN
=> Not so recent now...
4. for detailed description of DDPG.
=> for detailed descriptions of DDPG.
5. It's not enough to explore
=> it's not enough to explore
6. To make better, DDPG used Ornstein-Uhlenbeck noise. On the other hands, TD3 added Gaussian noise to each action. 
=> In order to facilitate more exploration. TD3 adds Gaussian noise to each action, while DDPG uses Ornstein-Uhlenbeck noise.
7. In TD3 paper, it said the Ornstein-Uhlenbeck noise offered no performance benefits.
=> The TD3 paper states Ornstein-Uhlenbeck noise offered no performance benefits.
8. ActionNormalizer in _italic_.

**Comment by MrSyee** [comment]
I've modified documents with your review. I approve of this PR.

**Review by MrSyee — APPROVED** [review]

**Pull request merged**
