### PR TITLE
Add behavior cloning

### PR DESCRIPTION
**Pull request by MrSyee**
[Colab](https://colab.research.google.com/github/MrSyee/pg-is-all-you-need/blob/feature%2Fadd-bc/07.BC.ipynb)

@Curt-Park @mclearning2 

I've done to implement Behavior Cloning! It is easy in relative. Please review this PR.

image

### CODE REVIEW

**Comment by Curt-Park** [comment]
1. where we store our demonstration data
=> where we store **the** demonstration data
2. It computed only on the demonstration examples
=> It **computes** only on the demonstration examples
3. However it needs parametrized goals setting
=> **However,** it needs parametrized **goal settings**
4. the following noise parameters work better. The detailed reason is described in DDPGfD PR.
```
ou_noise_theta = 1.0
ou_noise_sigma = 0.1
```
bc

`test score:  -225.440497529612`

**Review by Curt-Park — APPROVED** [review]
Nice work

**Comment by mclearning2** [comment]
1. we draw ~~an~~ extra ND examples from RD
2. Using above loss prevents the learned policy from improving 
=> Using **the** above loss prevents the learned policy from improving
3. the ~~demonstratior~~ action is better than actor action
=> the **demonstrator** action is better than actor action
4. However it needs parametrized goals setting, which can be sampled the goal g at the ~~beggining~~ of every ~~epiosde~~
=>  However it needs **a** parametrized goals setting, which can be sampled the goal g at the **beginning** of every **episode**

**Comment by MrSyee** [comment]
@mclearning2 I'll modify them another PR.

**Pull request merged**
